Repository skyfrk/dhbw-vs-latex-template, pull requests merged in 2019-08, with the labels that each got.

#26 Update page margins
  template/header.tex
Labels: dhbw-required

#27 Feature/improve documentation
  README.md
  docs/prerequisites.md
  docs/writing.md
  template/dhbw-text-requirements-2017.md
Labels: enhancement

#30 Fix footnote sometimes not being at the bottom of the page
  README.md
  docs/writing.md
  template/header.tex
Labels: bug

#31 Fix independence notice \dotfill bug
  template/independence-notice.tex
Labels: bug

#32 Replace old build procedure with latexmk
  .travis.yml
  .vscode/settings.json
  README.md
  build.ps1
  build.sh
  content/text.tex
  docs/setup.md
  template/header.tex
  template/independence-notice.tex
  template/title.tex
Labels: enhancement

#35 Replace pdflatex with lualatex and add PlantUML support
  .gitignore
  .vscode/settings.json
  build.ps1
  build.sh
  content/text.tex
  docs/setup.md
  docs/writing.md
  template/header.tex
Labels: enhancement

#36 Little update
  .travis.yml
  README.md
  build.ps1
  build.sh
  content/assets/figure.png
  content/assets/title/company-logo.png
  content/assets/title/dhbw-vs-logo.png
  content/misc/acronyms.tex
  content/misc/config.tex
  content/misc/literature.bib
  content/text.tex
  docs/dhbw-text-requirements-2017.md
  docs/examples/.gitignore
  docs/examples/full/company-logo.png
  docs/examples/full/full.pdf
  docs/examples/full/full.tex
  docs/examples/full/literature.bib
  docs/examples/starter-advanced/company-logo.png
  docs/examples/starter-advanced/literature.bib
  docs/examples/starter-advanced/starter-advanced.pdf
  docs/examples/starter-advanced/starter-advanced.tex
  docs/examples/starter-recommended/company-logo.png
  docs/examples/starter-recommended/literature.bib
  docs/examples/starter-recommended/starter-recommended.pdf
  docs/examples/starter-recommended/starter-recommended.tex
  docs/setup.md
  docs/writing.md
  install_udhbwvst_tl.ps1
  install_udhbwvst_tl.sh
  root.tex
  src/dhbw-vs-logo.png
  src/udhbwvst-independence-notice.def
  src/udhbwvst-non-disclosure-notice.def
  src/udhbwvst-title.def
  src/udhbwvst.cls
  template/dhbw-bibstyle.tex
  template/dhbw-citestyle.tex
  template/header.tex
  template/title.tex
Labels: enhancement

#40 Add VSCode snippets
  .vscode/settings.json
  .vscode/udhbwvst.code-snippets
  docs/setup.md
  docs/writing.md
Labels: enhancement

#44 Improved title page
  README.md
  docs/examples/full/full.pdf
  docs/examples/starter-advanced/starter-advanced.pdf
  docs/examples/starter-recommended/starter-recommended.pdf
  src/udhbwvst-independence-notice.def
  src/udhbwvst-title.def
  src/udhbwvst.cls
Labels: enhancement

#45 Replace arconym with acro (CTAN packages)
  .vscode/udhbwvst.code-snippets
  docs/examples/full/full.pdf
  docs/examples/full/full.tex
  docs/examples/starter-advanced/starter-advanced.pdf
  docs/examples/starter-advanced/starter-advanced.tex
  docs/examples/starter-recommended/starter-recommended.pdf
  docs/examples/starter-recommended/starter-recommended.tex
  docs/writing.md
  src/udhbwvst.cls
Labels: enhancement
